'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('countries', [
      //ISO 3166 ALPHA-2
      { name: "Afganistán", code: "AF", prefix: "+93"},
      { name: "Islas de Åland", code: "AX", prefix: ""},
      { name: "Albania", code: "AL", prefix: "+355"},
      { name: "Argelia", code: "DZ", prefix: "+213"},
      { name: "Samoa Americana", code: "AS", prefix: "+685"},
      { name: "Andorra", code: "AD", prefix: "+376"},
      { name: "Angola", code: "AO", prefix: "+244"},
      { name: "Anguila", code: "AI", prefix: "+1-264"},
      { name: "Antártida", code: "AQ", prefix: ""},
      { name: "Antigua y Barbuda", code: "AG", prefix: "+1-268"},
      { name: "Argentina", code: "AR", prefix: "+54"},
      { name: "Armenia", code: "AM", prefix: "+374"},
      { name: "Aruba", code: "AW", prefix: "+297"},
      { name: "Australia", code: "AU", prefix: "+61"},
      { name: "Austria", code: "AT", prefix: "+43"},
      { name: "Azerbaiyán", code: "AZ", prefix: "+994"},
      { name: "Bahamas", code: "BS", prefix: "+1-242"},
      { name: "Baréin", code: "BH", prefix: "+973"},
      { name: "Bangladesh", code: "BD", prefix: ""},
      { name: "Barbados", code: "BB", prefix: "+1-246"},
      { name: "Bielorrusia", code: "BY", prefix: "+375"},
      { name: "Bélgica", code: "BE", prefix: "+32"},
      { name: "Belice", code: "BZ", prefix: "+501"},
      { name: "Benín", code: "BJ", prefix: "+229"},
      { name: "Bermuda", code: "BM", prefix: "+1-441"},
      { name: "Bután", code: "BT", prefix: "+975"}, 
      { name: "Bolivia", code: "BO", prefix: "+591"},
      { name: "Bonaire, San Eustaquio y Saba", code: "BQ", prefix: "+599"},
      { name: "Bosnia y Herzegovina", code: "BA", prefix: "+387"},
      { name: "Botsuana", code: "BW", prefix: "+267"},
      { name: "Isla Bouvet", code: "BV", prefix: ""},
      { name: "Brasil", code: "BR", prefix: "+55"}, 
      { name: "Territorio Británico del Océano Índico", code: "IO", prefix: ""},
      { name: "Islas Vírgenes Británicas", code: "VG", prefix: "+1-284"},
      { name: "Brunei", code: "BN", prefix: "+673"},
      { name: "Bulgaria", code: "BG", prefix: "+359"},
      { name: "Burkina Faso", code: "BF", prefix: "+226"},
      { name: "Burundi", code: "BI", prefix: "+257"},
      { name: "Camboya", code: "KH", prefix: "+855"},
      { name: "Camerún", code: "CM", prefix: "+237"},
      { name: "Canadá", code: "CA", prefix: "+1"},
      { name: "Cabo Verde", code: "CV", prefix: "+238"},
      { name: "Islas Caimán", code: "KY", prefix: "+1-345"},
      { name: "República de África Central", code: "CF", prefix: ""},
      { name: "Chad", code: "TD", prefix: "+235"},
      { name: "Chile", code: "CL", prefix: "+56"},
      { name: "China", code: "CN", prefix: "+86"},
      { name: "Isla de Pascua", code: "CX", prefix: ""},
      { name: "Islas Cocos", code: "CC", prefix: ""},
      { name: "Colombia", code: "CO", prefix: "+57"},
      { name: "Comoras", code: "KM", prefix: "+269"},
      { name: "Islas Cook", code: "CK", prefix: "+682"},
      { name: "Costa Rica", code: "CR", prefix: "+506"},
      { name: "Croacia", code: "HR", prefix: "+385"},
      { name: "Cuba", code: "CU", prefix: "+53"},
      { name: "Curazao", code: "CW", prefix: "+599"},
      { name: "Chipre", code: "CY", prefix: "+357"},
      { name: "República Checa", code: "CZ", prefix: "+420"},
      { name: "República Democrática del Congo", code: "CD", prefix: "+243"},
      { name: "Dinamarca", code: "DK", prefix: "+45"},
      { name: "Yibuti", code: "DJ", prefix: "+253"},
      { name: "Dominica", code: "DM", prefix: "+1-767"},
      { name: "República Dominicana", code: "DO", prefix: "1-809, +1-829 y +1-849"},
      { name: "Timor Oriental", code: "TL", prefix: "+670"},
      { name: "Ecuador", code: "EC", prefix: "+593"}, 
      { name: "Egipto", code: "EG", prefix: "+20"}, 
      { name: "El Salvador", code: "SV", prefix: "+503"},
      { name: "Guinea Ecuatorial", code: "GQ", prefix: "+240"},
      { name: "Eritrea", code: "ER", prefix: "+291"},
      { name: "Estonia", code: "EE", prefix: "+372"},
      { name: "Etiopía", code: "ET", prefix: "+251"},
      { name: "Islas Malvinas", code: "FK", prefix: "+500"},
      { name: "Islas Faroe", code: "FO", prefix: ""},
      { name: "Fiji", code: "FJ", prefix: ""},
      { name: "Finlandia", code: "FI", prefix: "+358"},
      { name: "Francia", code: "FR", prefix: "+33"},
      { name: "Guayana Francesa", code: "GF", prefix: "+594"},
      { name: "Polinesia Francesa", code: "PF", prefix: "+689"},
      { name: "Territorios del sur Franceses", code: "TF", prefix: ""},
      { name: "Gabón", code: "GA", prefix: "+241"},
      { name: "Gambia", code: "GM", prefix: "+220"},
      { name: "Georgia", code: "GE", prefix: "+995"},
      { name: "Alemania", code: "DE", prefix: "+49"},
      { name: "Ghana", code: "GH", prefix: "+233"},
      { name: "Gibraltar", code: "GI", prefix: "+350"},
      { name: "Grecia", code: "GR", prefix: "+30"},
      { name: "Groenlandia", code: "GL", prefix: "+299"},
      { name: "Granada", code: "GD", prefix: "+1-473"},
      { name: "Guadalupe", code: "GP", prefix: "+590"},
      { name: "Guam", code: "GU", prefix: "+1-671"},
      { name: "Guatemala", code: "GT", prefix: "+502"},
      { name: "Guernsey", code: "GG", prefix: ""},
      { name: "Guinea", code: "GN", prefix: "+224"},
      { name: "Guinea Bissau", code: "GW", prefix: "+245"},
      { name: "Guyana", code: "GY", prefix: "+592"},
      { name: "Haití", code: "HT", prefix: "+509"},
      { name: "Islas Heard y McDonald", code: "HM", prefix: ""},
      { name: "Honduras", code: "HN", prefix: "+504"},
      { name: "Hong Kong", code: "HK", prefix: "+852"},
      { name: "Hungría", code: "HU", prefix: "+36"},
      { name: "Islandia", code: "IS", prefix: "+354"},
      { name: "India", code: "IN", prefix: "+91"},
      { name: "Indonesia", code: "ID", prefix: "+62"}, 
      { name: "Irán", code: "IR", prefix: "+98"},
      { name: "Irak", code: "IQ", prefix: "+964"},
      { name: "Irlanda", code: "IE", prefix: "+353"},
      { name: "Isla de Man", code: "IM", prefix: ""},
      { name: "Israel", code: "IL", prefix: "+972"},
      { name: "Italia", code: "IT", prefix: "+39"},
      { name: "Costa de Marfil", code: "CI", prefix: "+225"},
      { name: "Jamaica", code: "JM", prefix: "+1-876 y +1-658"},
      { name: "Japón", code: "JP", prefix: "+81"},
      { name: "Jersey", code: "JE", prefix: ""},
      { name: "Jordania", code: "JO", prefix: "+962"},
      { name: "Kazajistán", code: "KZ", prefix: "+7"},
      { name: "Kenia", code: "KE", prefix: "+254"},
      { name: "Kiribati", code: "KI", prefix: "+686"},
      { name: "Kosovo", code: "XK", prefix: "+383"},
      { name: "Kuwait", code: "KW", prefix: "+965"},
      { name: "Kirguistán", code: "KG", prefix: "+996"},
      { name: "Laos", code: "LA", prefix: "+856"},
      { name: "Letonia", code: "LV", prefix: "+371"},
      { name: "Líbano", code: "LB", prefix: "+961"},
      { name: "Lesoto", code: "LS", prefix: "+266"},
      { name: "Liberia", code: "LR", prefix: "+231"},
      { name: "Libia", code: "LY", prefix: "+218"},
      { name: "Liechtenstein", code: "LI", prefix: "+423"},
      { name: "Lituania", code: "LT", prefix: "+370"},
      { name: "Luxemburgo", code: "LU", prefix: "+352"},
      { name: "Macao", code: "MO", prefix: "+853"},
      { name: "Macedonia", code: "MK", prefix: "+389"},
      { name: "Madagascar", code: "MG", prefix: "+261"},
      { name: "Malaui", code: "MW", prefix: "+265"},
      { name: "Malasia", code: "MY", prefix: "+60"},
      { name: "Maldivas", code: "MV", prefix: "+960"},
      { name: "Malí", code: "ML", prefix: "+223"},
      { name: "Malta", code: "MT", prefix: "+356"},
      { name: "Islas Marshall", code: "MH", prefix: "+692"},
      { name: "Martinica", code: "MQ", prefix: "+596"},
      { name: "Mauritania", code: "MR", prefix: "+222"},
      { name: "Mauricio", code: "MU", prefix: "+230"},
      { name: "Mayotte", code: "YT", prefix: "+262"},
      { name: "México", code: "MX", prefix: "+52"},
      { name: "Micronesia", code: "FM", prefix: "+691"},
      { name: "Moldavia", code: "MD", prefix: "+373"},
      { name: "Mónaco", code: "MC", prefix: "+377"},
      { name: "Mongolia", code: "MN", prefix: "+976"},
      { name: "Montenegro", code: "ME", prefix: "+382"},
      { name: "Montserrat", code: "MS", prefix: "+1-664"},
      { name: "Marruecos", code: "MA", prefix: "+212"},
      { name: "Mozambique", code: "MZ", prefix: "+258"},
      { name: "Myanmar", code: "MM", prefix: ""},
      { name: "Namibia", code: "NA", prefix: "+264"},
      { name: "Nauru", code: "NR", prefix: "+674"},
      { name: "Nepal", code: "NP", prefix: "+977"},
      { name: "Países Bajos", code: "NL", prefix: "+31"},
      { name: "Antillas Holandesas", code: "AN", prefix: ""},
      { name: "Nueva Caledonia", code: "NC", prefix: "+687"},
      { name: "Nueva Zelanda", code: "NZ", prefix: "+64"},
      { name: "Nicaragua", code: "NI", prefix: "+505"},
      { name: "Níger", code: "NE", prefix: "+227"},
      { name: "Nigeria", code: "NG", prefix: "+234"},
      { name: "Niue", code: "NU", prefix: "+683"},
      { name: "Isla Norfolk", code: "NF", prefix: "+672"},
      { name: "Corea del Norte", code: "KP", prefix: "+850"},
      { name: "Islas Marianas del Norte", code: "MP", prefix: "+1-670"},
      { name: "Noruega", code: "NO", prefix: "+47"},
      { name: "Omán", code: "OM", prefix: "+968"},
      { name: "Pakistán", code: "PK", prefix: "+92"},
      { name: "Palaos", code: "PW", prefix: "+680"},
      { name: "Palestina", code: "PS", prefix: "+970"},
      { name: "Panamá", code: "PA", prefix: "+507"},
      { name: "Papúa Nueva Guinea", code: "PG", prefix: "+675"},
      { name: "Paraguay", code: "PY", prefix: "+595"},
      { name: "Perú", code: "PE", prefix: "+51"},
      { name: "Filipinas", code: "PH", prefix: "+63"},
      { name: "Islas Pitcairn", code: "PN", prefix: "+64"},
      { name: "Polonia", code: "PL", prefix: "+48"},
      { name: "Portugal", code: "PT", prefix: "+351"},
      { name: "Puerto Rico", code: "PR", prefix: "+1-787, +1-939"}, 
      { name: "Catar", code: "QA", prefix: "+974"},
      { name: "República del Congo", code: "CG", prefix: "+242"},
      { name: "Reunión", code: "RE", prefix: "+262"},
      { name: "Rumanía", code: "RO", prefix: "+40"},
      { name: "Rusia", code: "RU", prefix: "+7"},
      { name: "Ruanda", code: "RW", prefix: "+250"},
      { name: "San Bartolomé", code: "BL", prefix: "+590"},
      { name: "Santa Elena", code: "SH", prefix: "+290"},
      { name: "San Cristóbal y Nieves", code: "KN", prefix: "+1-869"},
      { name: "Santa Lucía", code: "LC", prefix: "+1-758"},
      { name: "San Martín", code: "MF", prefix: "+1-721"},
      { name: "San Pedro y Miguelón", code: "PM", prefix: "+508"},
      { name: "San Vicente y las Granadinas", code: "VC", prefix: "+1-784"},
      { name: "Samoa Occidental", code: "WS", prefix: "+685"},
      { name: "San Marino", code: "SM", prefix: "+378"},
      { name: "Santo Tomé y Príncipe", code: "ST", prefix: "+239"},
      { name: "Arabia Saudita", code: "SA", prefix: "+966"},
      { name: "Senegal", code: "SN", prefix: "+221"},
      { name: "Serbia", code: "RS", prefix: "+381"},
      { name: "Montenegro", code: "CS", prefix: "+382"},
      { name: "Seychelles", code: "SC", prefix: "+248"},
      { name: "Sierra Leona", code: "SL", prefix: "+232"},
      { name: "Singapur", code: "SG", prefix: "+65"},
      { name: "San Martín", code: "SX", prefix: "+1-721"},
      { name: "Eslovaquia", code: "SK", prefix: "+421"},
      { name: "Eslovenia", code: "SI", prefix: "+386"},
      { name: "Islas Salomón", code: "SB", prefix: "+677"},
      { name: "Somalia", code: "SO", prefix: "+252"},
      { name: "Sudáfrica", code: "ZA", prefix: "+27"},
      { name: "Islas Georgia del Sur y Sandwich del Sur", code: "GS", prefix: "+500"},
      { name: "Corea del Sur", code: "KR", prefix: "+82"},
      { name: "Sudán del Sur", code: "SS", prefix: "+211"},
      { name: "España", code: "ES", prefix: "+34"},
      { name: "Sri Lanka", code: "LK", prefix: "+94"},
      { name: "Sudán", code: "SD", prefix: "+249"},
      { name: "Surinam", code: "SR", prefix: "+597"},
      { name: "Islas Svalbard y Jan Mayen", code: "SJ", prefix: ""},
      { name: "Suazilandia", code: "SZ", prefix: "+268"},
      { name: "Suecia", code: "SE", prefix: "+46"},
      { name: "Suiza", code: "CH", prefix: "+41"},
      { name: "Siria", code: "SY", prefix: "+963"},
      { name: "Taiwán", code: "TW", prefix: "+886"},
      { name: "Tayikistán", code: "TJ", prefix: "+992"},
      { name: "Tanzania", code: "TZ", prefix: "+255"},
      { name: "Tailandia", code: "TH", prefix: "+66"},
      { name: "República Togolesa", code: "TG", prefix: "+228"},
      { name: "Islas Tokelau", code: "TK", prefix: "+690"},
      { name: "Tonga", code: "TO", prefix: "+676"},
      { name: "Trinidad y Tobago", code: "TT", prefix: "+1-868"},
      { name: "Túnez", code: "TN", prefix: "+216"},
      { name: "Turquía", code: "TR", prefix: "+90"},
      { name: "Turkmenistán", code: "TM", prefix: "+993"},
      { name: "Islas Turcos y Caicos", code: "TC", prefix: "+1-649"},
      { name: "Tuvalu", code: "TV", prefix: "+688"},
      { name: "Islas Vírgenes de los EE.UU.", code: "VI", prefix: "+1-340"},
      { name: "Uganda", code: "UG", prefix: "+256"},
      { name: "Ucrania", code: "UA", prefix: "+380"},
      { name: "Emiratos Árabes Unidos", code: "AE", prefix: "+971"},
      { name: "Reino Unido", code: "GB", prefix: "+44"},
      { name: "Estados Unidos (USA)", code: "US", prefix: "+1"},
      { name: "Islas menores alejadas de los Estados Unidos", code: "UM", prefix: ""},
      { name: "Uruguay", code: "UY", prefix: "+598"},
      { name: "Uzbekistán", code: "UZ", prefix: "+998"},
      { name: "Vanuatu", code: "VU", prefix: "+678"},
      { name: "Vaticano", code: "VA", prefix: "+379"},
      { name: "Venezuela", code: "VE", prefix: "+58"},
      { name: "Vietnam", code: "VN", prefix: "+84"},
      { name: "Wallis y Futuna", code: "WF", prefix: "+681"},
      { name: "Sahara Occidental", code: "EH", prefix: ""},
      { name: "Yemen", code: "YE", prefix: "+967"},
      { name: "Zambia", code: "ZM", prefix: "+260"},
      { name: "Zimbabue", code: "ZW", prefix: "+263"}
  ]);
  },

  down: async (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('countries', null, {});

  }
};
